# Generated by Django 5.2.4 on 2025-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="active_at",
            field=models.DateTimeField(null=True),
        ),
    ]
