# Generated by Django 5.2.4 on 2025-07-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documents_active_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
